OENIK_PROG3_2020_2_BUSKF6/FootballRecord.Web/Models/Player.cs
// <copyright file="Player.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace FootballRecord.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Player class.
    /// </summary>
    public class Player
    {
        /// <summary>
        /// Gets or sets player Id.
        /// </summary>
        [Display(Name = "Player Id")]
        [Required]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets Surname.
        /// </summary>
        [Display(Name = "Player Surname")]
        [Required]
        [StringLength(20, MinimumLength = 2)]
        public string Surname { get; set; }

        /// <summary>
        /// Gets or sets player Firstname.
        /// </summary>
        [Display(Name = "Player Firstname")]
        [Required]
        [StringLength(20, MinimumLength = 2)]
        public string Firstname { get; set; }

        /// <summary>
        /// Gets or sets player JerseyNumber.
        /// </summary>
        [Display(Name = "Player Jersey number")]
        [Required]
        public int JerseyNumber { get; set; }

       /// <summary>
       /// Gets or sets player DateOfbirth.
       /// </summary>
        [Display(Name = "Player Date Of Birth")]
        [Required]
        public string DateOfBirth { get; set; }

        /// <summary>
        /// Gets or sets player performance.
        /// </summary>
        [Display(Name = "Player Performance")]
        [Required]
        public int Performance { get; set; }
    }
}

OENIK_PROG3_2020_2_BUSKF6/FootballRecord.Web/Controllers/PlayersController.cs
// <copyright file="PlayersController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace FootballRecord.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using FootballRecord.Logic;
    using FootballRecord.Web.Models;
    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// PlayersController.
    /// </summary>
    public class PlayersController : Controller
    {
        private IPlayerLogic logic;
        private IMapper mapper;
        private PlayerListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="PlayersController"/> class.
        /// PlayersController constructor.
        /// </summary>
        /// <param name="logic">Logic.</param>
        /// <param name="mapper">Mapper.</param>
        public PlayersController(IPlayerLogic logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            vm = new PlayerListViewModel();
            vm.EditedPlayer = new Models.Player();

            var players = logic.GetAllPlayers();
            vm.ListOfPlayers = mapper.Map<IList<Data.Models.Player>, List<Models.Player>>(players);
        }

        /// <summary>
        /// Index.
        /// </summary>
        /// <returns>View.</returns>
        public IActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("PlayersIndex", vm);
        }

        private Models.Player GetPlayerModel(int id)
        {
            Data.Models.Player onePlayer = logic.GetPlayerById(id);
            return mapper.Map<Data.Models.Player, Models.Player>(onePlayer);
        }

        /// <summary>
        /// Details.
        /// </summary>
        /// <param name="id">Player Id.</param>
        /// <returns>View.</returns>
        public IActionResult Details(int id)
        {
            return View("PlayersDetails", GetPlayerModel(id));
        }

        /// <summary>
        /// Remove.
        /// </summary>
        /// <param name="id">Player Id.</param>
        /// <returns>View.</returns>
        public IActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete FAIL";

            if (logic.DeletePlayer(id))
            {
                TempData["editResult"] = "Delete OK";
            }

            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Edit.
        /// </summary>
        /// <param name="id">Player Id.</param>
        /// <returns>View.</returns>
        public IActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedPlayer = GetPlayerModel(id);
            return View("PlayersIndex", vm);
        }

        /// <summary>
        /// Edit.
        /// </summary>
        /// <param name="player">Model Player.</param>
        /// <param name="editAction">EditAction.</param>
        /// <returns>View.</returns>
        [HttpPost]
        public IActionResult Edit(Models.Player player, string editAction)
        {
            if (ModelState.IsValid && player != null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    try
                    {
                        logic.AddPlayer(player.Surname, player.Firstname, player.JerseyNumber, player.DateOfBirth, player.Performance, 1);
                    }
                    catch (ArgumentException ex)
                    {
                        TempData["editResult"] = "AddPlayer FAIL: " + ex.Message;
                    }
                }
                else
                {
                    if (!logic.UpdatePlayer(player.Id, player.Surname, player.Firstname, player.JerseyNumber, player.DateOfBirth, player.Performance))
                    {
                        TempData["editResult"] = "Edit FAIL";
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedPlayer = player;
                return View("PlayersIndex", vm);
            }
        }
    }
}

OENIK_PROG3_2020_2_BUSKF6/FootballRecord.Web/Views/Players/PlayersDetails.cshtml
@model FootballRecord.Web.Models.Player

@{
    ViewData["Title"] = "PlayersDetails";
}

<h2>Datasheet of one player</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Id)</td>
        <td>@Html.DisplayFor(m => m.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Surname)</td>
        <td>@Html.DisplayFor(m => m.Surname)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Firstname)</td>
        <td>@Html.DisplayFor(m => m.Firstname)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.JerseyNumber)</td>
        <td>@Html.DisplayFor(m => m.JerseyNumber)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.DateOfBirth)</td>
        <td>@Html.DisplayFor(m => m.DateOfBirth)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Performance)</td>
        <td>@Html.DisplayFor(m => m.Performance)</td>
    </tr>

</table>

OENIK_PROG3_2020_2_BUSKF6/FootballRecord.Web/Views/Players/PlayersEdit.cshtml
@model FootballRecord.Web.Models.Player

<h2>PlayersEdit</h2>

@using (Html.BeginForm("Edit", "Players"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Surname)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Surname)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Firstname)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Firstname)</div>

    <div class="editor-label">@Html.LabelFor(m => m.JerseyNumber)</div>
    <div class="editor-field">@Html.EditorFor(m => m.JerseyNumber)</div>

    <div class="editor-label">@Html.LabelFor(m => m.DateOfBirth)</div>
    <div class="editor-field">@Html.EditorFor(m => m.DateOfBirth)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Performance)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Performance)</div>

    <input type="submit" value="SEND" />

}

OENIK_PROG3_2020_2_BUSKF6/FootballRecord.Web/Views/Players/PlayersIndex.cshtml
@model FootballRecord.Web.Models.PlayerListViewModel

@{
    ViewData["Title"] = "PlayersIndex";
}
<h2>Players Index</h2>

<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("PlayersEdit", Model.EditedPlayer)

@await Html.PartialAsync("PlayersList", Model.ListOfPlayers) 

OENIK_PROG3_2020_2_BUSKF6/FootballRecord.Web/Views/Players/PlayersList.cshtml
@model IEnumerable<FootballRecord.Web.Models.Player>
    
<h2>PlayersList</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database!</p>
}
else
{ 
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Firstname)</th>
            <th>@Html.DisplayNameFor(m => m.First().Surname)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Modify</th>
        </tr>
        @foreach (var player in Model)
        { 
            <tr>
                <td>@Html.DisplayFor(m => player.Firstname)</td>
                <td>@Html.DisplayFor(m => player.Surname)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = player.Id })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = player.Id })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = player.Id })</td>
             </tr>
        }



    </table>


}